### ISSUE TITLE
Error in executing create view statement.

### ISSUE THREAD

**Issue by donnyhardyanto** [tanimutomo/sqlfile#10]
Fail to execute create view statement:

create view A
as
select B.*
from B;
 
The root cause because as statement is in separate line (because for automated formating in some IDE).

By replacing line  l := strings.Join(ncls, "") to  l := strings.Join(ncls, " ") will solve the problem

**Comment by eparisot-mitsa** [comment]
Same issue here...

PR done 

https://github.com/tanimutomo/sqlfile/pull/12

**Comment by tanimutomo** [comment]
@eparisot-mitsa 
Thank you for creating pull request!
i closed this issue because merged the PR.
